- id: clickx-icon
  name: Convert images to icons
  description: Convert image files to Windows ICO format with multiple sizes
  entry: clickx icon
  additional_dependencies:
    - pillow
  language: python
  files: ^$
